alpaca:
  api_key: PK52W7Q87YFYQQOREGIQ
  api_secret: NINtBWhPFeRSgnMe8nralpnJJ8WqTm2rklDkYblc
  base_url: https://paper-api.alpaca.markets
  data_url: https://data.alpaca.markets
backtest:
  commission: 1.0
  end_date: '2023-06-30'
  initial_capital: 300
  max_signals_per_day: 40
  metrics:
  - total_return
  - sharpe_ratio
  - max_drawdown
  - win_rate
  - profit_factor
  quarters:
    q1_2024:
      end_date: '2024-03-31'
      start_date: '2024-01-01'
    q2_2023:
      end_date: '2023-06-30'
      start_date: '2023-04-01'
    q3_2023:
      end_date: '2023-09-30'
      start_date: '2023-07-01'
    q4_2023:
      end_date: '2023-12-31'
      start_date: '2023-10-01'
  start_date: '2023-01-01'
holding_period: 3
initial_capital: 300
log_level: INFO
max_positions: 40
mode: paper
paths:
  backtest_results: backtest_results
  data: ./data
  logs: ./logs
  models: ./models
  performance: performance/SP500Strategy
  plots: plots
  results: ./results
  stop_loss_history: stop_loss_history.csv
  trades: trades
portfolio:
  cash_allocation: 0.9
  max_positions: 10
  position_size: 0.1
  stop_loss: 0.02
  take_profit: 0.05
strategy:
  atr_period: 10
  base_position_size: 1000
  bb_period: 15
  holding_period: 3
  include_midcap: true
  initial_capital: 300
  macd_fast: 8
  macd_signal: 5
  macd_slow: 17
  market_regime:
    change_period: 5
    enabled: true
    sma_long_period: 20
    sma_short_period: 5
  max_capital_per_direction: 60000
  max_positions: 100
  midcap_stocks:
    boost_factor: 1.2
    large_cap_percentage: 70
    max_symbols: 50
    min_avg_volume: 500000
    position_factor: 0.8
    symbols:
    - AXON
    - DECK
    - BLDR
    - PODD
    - LSCC
    - EXAS
    - CSGP
    - NATI
    - UTHR
    - HALO
    - CGNX
    - SYNA
    - PNFP
    - FOXF
    - QLYS
    - CRVL
    - OMCL
    - CVLT
    - XPEL
    - NSIT
  position_sizing:
    base_position_pct: 10
    long_multiplier: 3.0
    short_multiplier: 1.0
    tier_multipliers:
      Below Threshold (<0.8): 0.0
      "Tier 1 (\xE2\u2030\xA50.9)": 3.0
      Tier 2 (0.8-0.9): 1.5
    "tier_multipliers['Tier 1 (\u22650":
      9)']: 3.0
    tier_multipliers['Tier 2 (0:
      8-0:
        9)']: 1.5
  rsi_period: 10
  sector_adjustments:
    enabled: true
    sector_etfs:
    - XLK
    - XLF
    - XLV
    - XLE
    - XLI
    - XLY
    - XLP
    - XLB
    - XLU
    - XLRE
    - XLC
    sector_weights:
      Communication Services: 2.0
      Consumer Discretionary: 1.3
      Consumer Staples: 1.1
      Energy: 1.1
      Financials: 1.4
      Healthcare: 1.4
      Industrials: 1.8
      Materials: 1.2
      Real Estate: 0.8
      Technology: 1.5
      Utilities: 1.5
  signal_thresholds:
    long: 0.7
    min_score: 0.7
    short: 0.8
    tier_1: 0.9
    tier_2: 0.8
    tier_3: 0.7
    tier_4: 0.6
  stop_loss:
    adaptive:
      enabled: true
      market_regime_scaling: true
      sector_regime_scaling: true
      signal_quality_scaling: true
      time_scaling: true
      volatility_scaling: true
    enabled: true
    long_threshold: '-0.02'
    short_threshold: -0.01
    trailing:
      distance: 0.01
      enabled: true
      profit_tiers:
        tier1:
          lock_in: 7.0
          retain_pct: 0.7
          threshold: 10.0
        tier2:
          lock_in: 3.0
          retain_pct: 0.6
          threshold: 5.0
        tier3:
          lock_in: 1.0
          retain_pct: 0.5
          threshold: 3.0
